const gameType = [
    "Action",
    "Adventure",
    "Role-Playing Game (RPG)",
    "Simulation",
    "Strategy",
    "Sports",
    "Racing",
    "Puzzle",
    "Platformer",
    "Fighting",
    "Horror",
    "Sandbox",
    "Stealth",
    "Survival",
    "Open World",
    "Multiplayer Online Battle Arena (MOBA)",
    "Massively Multiplayer Online Role-Playing Game (MMORPG)",
    "Real-Time Strategy (RTS)",
    "Turn-Based Strategy (TBS)",
    "Educational",
    "Music",
    "Virtual Reality (VR)",
    "Augmented Reality (AR)",
    "Casual",
    "Indie",
]

export default gameType
